// Code generated by sqlc. DO NOT EDIT.
// source: character.sql

package db

import (
	"context"
)

const createCharacter = `-- name: CreateCharacter :one
INSERT INTO characters (
    name
) 
VALUES (
    $1
) RETURNING id, name
`

func (q *Queries) CreateCharacter(ctx context.Context, name string) (Character, error) {
	row := q.db.QueryRowContext(ctx, createCharacter, name)
	var i Character
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
